version: "3.7"

services:
  backend:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - .env.db
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - database
    command: sh -c "/wait-for-it.sh database:5432 -- python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres
    env_file:
      - .env.db
    ports:
      - "5434:5432"
    volumes:
      - ./db_backup:/var/lib/posgresql/data
    restart: on-failure

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
