# Generated by Django 3.2.8 on 2021-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('creation_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
